# This will push changes to the munki-repo to s3 bucket

validate:
  image: ubuntu
  stage: test
  script: ci_scripts/check_for_typos.sh

roll_out:
  image: python:2
  stage: deploy
  # when: manual
  # only: master
  script:
    - ci_scripts/prep_deploy.sh
    - ci_scripts/nyan.py
