# This will push changes to the munki-repo to s3 bucket

deploy:
  image: macjustice/git-lfs-s3cmd
  stage: deploy
  script:
    - ./s3-deploy.sh
  variables:
    BUCKET_PATH: "s3://gitlab-munki-demo"
